import { cn } from "@/lib/utils";

/**
 * The ReachMe verified badge.
 *
 * A scalloped twelve-point starburst — the same silhouette
 * vocabulary X uses for its verified mark — rebuilt in ReachMe's
 * own palette so it belongs to no other product. The starburst
 * is filled with --ink, the inset check is drawn in --page (the
 * warm off-white). No blue, no plastic, no tech-company sheen.
 *
 * Sized via the `size` prop to match the surrounding type. For
 * the public profile headline (1.6rem), 18px reads correctly.
 */
export function VerifiedBadge({
  size = 16,
  className,
}: {
  size?: number;
  className?: string;
}) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      role="img"
      aria-label="Verified"
      className={cn("inline-block shrink-0", className)}
    >
      {/*
       * Scalloped 12-lobe starburst. Generated by alternating
       * outer and inner radii around the centre — outer at 11.5,
       * inner at 9.7 — for a subtle, considered scallop that
       * never reads decorative.
       */}
      <path
        fill="hsl(var(--ink))"
        d="M12 0.5 L13.42 2.6 L15.83 1.49 L16.6 4.04 L19.18 3.65 L19.18 6.31 L21.61 7.27 L20.79 9.81 L22.78 11.43 L21.16 13.55 L22.31 15.95 L20.06 17.18 L20.18 19.83 L17.61 19.99 L16.78 22.51 L14.36 21.47 L12.65 23.5 L12 23.05 L11.35 23.5 L9.64 21.47 L7.22 22.51 L6.39 19.99 L3.82 19.83 L3.94 17.18 L1.69 15.95 L2.84 13.55 L1.22 11.43 L3.21 9.81 L2.39 7.27 L4.82 6.31 L4.82 3.65 L7.4 4.04 L8.17 1.49 L10.58 2.6 Z"
      />
      <path
        fill="none"
        stroke="hsl(var(--page))"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M7.6 12.4 L10.6 15.3 L16.4 9.2"
      />
    </svg>
  );
}
